#pragma once

#include<stdint.h>

constexpr auto NORTH_AMERICA_REINFORCEMENT = 5;
constexpr auto SOUTH_AMERICA_REINFORCEMENT = 2;
constexpr auto AFRICA_REINFORCEMENT = 3;
constexpr auto EUROPE_REINFORCEMENT = 5;
constexpr auto ASIA_REINFORCEMENT = 7;
constexpr auto AUSTRALIA_REINFORCEMENT = 2;

enum class LandIndex : uint8_t
{
	// North America
	ALASKA,
	NORTHWEST_TERRIOTRY,
	GREENLAND,
	ALBERTA,
	ONTARIO,
	QUEBEC,
	WESTERN_UNITED_STATES,
	EASTERN_UNITED_STATES,
	CENTRAL_AMERICA,

	// South america
	VENEZUELA,
	PERU,
	BRAZIL,
	ARGENTINA,

	//Europe
	ICELAND,
	GREAT_BRITAIN,
	SCANDINAVIA,
	UKRAINE,
	NORTHERN_EUROPE,
	SOUTHERN_EUROPE,
	WESTERN_EUROPE,

	//Africa
	NORTH_AFRICA,
	EGYPT,
	CONGO,
	EAST_AFRICA,
	SOUTH_AFRICA,
	MADAGASKAR,

	// Asia
	URAL,
	SIBERIA,
	YAKUTSK,
	KAMCHATKA,
	IRKUTSK,
	JAPAN,
	MONGOLIA,
	AFGHANISTAN,
	CHINA,
	MIDDLE_EAST,
	INDIA,
	SIAM,

	//
	INDONESIA,
	NEW_GUINEA,
	WESTERN_AUSTRALIA,
	EASTERN_AUSTRALIA,

	Count,
	None
};

constexpr int LAND_INDEX_SIZE = static_cast<int>(LandIndex::Count);
constexpr int CARDS_INDEX_SIZE = LAND_INDEX_SIZE + 1;